### ISSUE TITLE
While compiling in Ubuntu22 and Julia_1.8.5

### ISSUE THREAD

**Issue by sylviankahane** [g-insana/CMPlot.jl#4]
ERROR: Data Error : jl_FiPmzufQF88GikyY~
┌ Warning: failed to extract archive downloaded from https://pkg.julialang.org/package/08abe8d2-0d0c-5749-adfa-8a2ac140af0d/96f6db03ab535bdb901300f88335257b0018689d
└ @ Pkg.Operations /cache/build/default-amdci4-2/julialang/julia-release-1-dot-8/usr/share/julia/stdlib/v1.8/Pkg/src/Operations.jl:

**Comment by g-insana** [comment]
I've just tried a fresh install of Julia 1.8.5 in Ubuntu 22 and on MacOS.

I don't see any issues with it and cannot reproduce your error.

Could it be you had some problems with the download?

Please see attached log_files of building and testing operations in both Ubuntu and MacOS.
[cmplot_julia185_macos_test.txt](https://github.com/g-insana/CMPlot.jl/files/10943646/cmplot_julia185_macos_test.txt)
[cmplot_julia185_ubuntu_test.txt](https://github.com/g-insana/CMPlot.jl/files/10943647/cmplot_julia185_ubuntu_test.txt)
